% ==================================================================
% SCENARIO ANALYSIS: THE PDP8 TRANSITION (2025-2050)
% Deterministic Simulation of a Permanent Renewable Expansion
% ==================================================================
clear all; close all; clc;

% 1. Run the Deterministic Model
% The initval, endval, and simul commands are INSIDE the .mod file.
% We just need to trigger it here.
dynare thesis_pdp8_ramp.mod noclearall nolog;

% 2. Plot the Results
% Access the global structures generated by Dynare
global M_ oo_ options_

figure('Name', 'PDP8 Transition Path (2025-2050)');
T = 1:100; % Plot 100 periods (25 years)

% Panel 1: The Renewable Push
subplot(2,2,1);
% Check if E_ren is endogenous (in thesis_pdp8.mod) or exogenous
id_E = strmatch('E_ren', M_.endo_names, 'exact');
if ~isempty(id_E)
    data_E = oo_.endo_simul(id_E, 1:100);
else
    % Fallback if you used the "Fixed" version where E_ren is exogenous
    id_E = strmatch('E_ren', M_.exo_names, 'exact');
    data_E = oo_.exo_simul(1:100, id_E)'; 
end
plot(T, data_E, 'b-', 'LineWidth', 2);
title('Renewable Capacity (E_{ren})');
grid on; ylabel('Capacity');

% Panel 2: The Reliability Trap
subplot(2,2,2);
plot(T, oo_.endo_simul(strmatch('u', M_.endo_names, 'exact'), 1:100), 'r-', 'LineWidth', 2);
title('Grid Reliability (u)');
grid on; ylabel('Utilization Rate');

% Panel 3: Investment Divergence
subplot(2,2,3);
plot(T, oo_.endo_simul(strmatch('I_b', M_.endo_names, 'exact'), 1:100), 'b-', 'LineWidth', 1.5); hold on;
plot(T, oo_.endo_simul(strmatch('I_g', M_.endo_names, 'exact'), 1:100), 'k--', 'LineWidth', 1.5);
legend('Private Batteries', 'Public Grid');
title('Investment Response');
grid on;

% Panel 4: Innovation
subplot(2,2,4);
plot(T, oo_.endo_simul(strmatch('A_bat', M_.endo_names, 'exact'), 1:100), 'g-', 'LineWidth', 2);
title('Battery Technology (A_{bat})');
grid on;